export const friends = [
  '(I Noldor) Finwe Noldoran',
  '(I Noldor) Miriel Perinde Serinde',
  '(I Noldor) Mahtan Aulendir (Urundil, Rusco)',
  '(I Vanyar) Indis The Fair',
  '(II Noldor) Feanor Curufinwe Feanaro',
  '(II Noldor) Nerdanel the Wise',
  '(III Noldor) Maethros the Tall (Dispossessed, Maitimo)',
  '(III Noldor) Maglor Macalaure Canafinwe',
  '(III Noldor) Celegorm the Fair (Turcafinwe, Tyelkormo)',
  '(III Noldor) Caranthir the Dark (Carnistir, Morifinwe)',
  '(III Noldor) Curufin the Crafty (Curufinwe, Atarinke)',
  '(III Noldor) Amrod (Ambarussa, Ambarto, Umbarto, Telufinwe)',
  '(III Noldor) Amras (Ambarussa, Diriel, Pityafinwe)',
  '(IV Noldor) Celebrimbor Telperinquer',
  '(II Noldor) Fingolfin Nolofinwe Arakano',
  '(II Noldor) Anarie Holiest',
  '(III Noldor) Fingon the Valiant (Findekano)',
  '(II Noldor) Finarfin Arafinwe',
  '(II Noldor) Findis (daughter Finwe and Indis)',
  '(II Noldor) Irime (daughter Finwe and Indis)',
  'Finrod Felagund',
  'Beren Erchamion',
  'Luthien Tinuviel',
  'Elu Tingol',
  'Tuor Eladar',
  'Idril Celebrindal',
  'Dior Eluchil',
  'Earendil Blessed',
  'Elwing The White',
  'Elrond Peredhel',
  'Elros Tar-Minyatur',
  'Aragorn Elessar',
  'Arven Evenstar',
  'Frodo Baggins',
  'Drogo Baggins',
  'Primula Baggins',
  'Bilbo Baggins',
  'Sem Gamgee',
  'Meriadoc (Merry) Brandybuck',
  'Peregrin (Pippin) Took',
];
