export const friends = [
  '(I Noldor) Finwe Noldoran',
  '(I Noldor) Miriel Perinde Serinde',
  '(I Noldor) Mahtan Aulendir (Urundil, Rusco)',
  '(I Vanyar) Indis The Fair',
  '(II Noldor) Feanor Curufinwe Feanaro',
  '(II Noldor) Nerdanel the Wise',
  '(III Noldor) Maethros the Tall (Dispossessed, Maitimo)',
  '(III Noldor) Maglor Macalaure Canafinwe',
  '(III Noldor) Celegorm the Fair (Turcafinwe, Tyelkormo)',
  '(III Noldor) Caranthir the Dark (Carnistir, Morifinwe)',
  '(III Noldor) Curufin the Crafty (Curufinwe, Atarinke)',
  '(IV Noldor) Celebrimbor Telperinquer',
  '(III Noldor) Amrod (Ambarussa, Ambarto, Umbarto, Telufinwe)',
  '(III Noldor) Amras (Ambarussa, Diriel, Pityafinwe)',
  '(II Noldor) Fingolfin Nolofinwe Arakano',
  '(II Noldor) Anarie Holiest',
  '(III Noldor) Fingon the Valiant (Findekano)',
  '(III Noldor) Turgon the Wise (Turukano)',
  '(III Noldor) Aredhel Ar-Feiniel, Irisse, Isfin',
  '(III Noldor) Argon Arakano',
  '(II Noldor) Finarfin Arafinwe',
  '(II Noldor) Findis (daughter Finwe and Indis)',
  '(II Noldor) Irime (daughter Finwe and Indis)',
  '(II Falmari) Earwen Swan-Maiden of Alqualonde',
  '(III Noldor) Finrod Felagund (Finarfin (in earlier texts), Ingoldo, Findarato/Artafinde, Nom or Nomin)',
  '(III Noldor) Angrod Angaráto',
  '(III Noldor) Eldalote (Edhellos)',
  '(IV Noldor) Orodreth (Artaher, Arothir, Artaresto)',
  '(V Noldor) Findulias (Faelivrin)',
  '(III Noldor) Aegnor (Egnor, Aikanár, Aikanáro)',
  '(III Noldor) Galadriel (Alatariel, Artanis, Nerwen)',
  'Beren Erchamion',
  'Luthien Tinuviel',
  'Elu Tingol',
  'Tuor Eladar',
  'Idril Celebrindal',
  'Dior Eluchil',
  'Earendil Blessed',
  'Elwing The White',
  'Elrond Peredhel',
  'Elros Tar-Minyatur',
  'Aragorn Elessar',
  'Arven Evenstar',
  'Frodo Baggins',
  'Drogo Baggins',
  'Primula Baggins',
  'Bilbo Baggins',
  'Sem Gamgee',
  'Meriadoc (Merry) Brandybuck',
  'Peregrin (Pippin) Took',
];
