export const friends = [
  'Finrod Felagund',
  'Beren Erchamion',
  'Luthien Tinuviel',
  'Elu Tingol',
  'Tuor Eladar',
  'Idril Celebrindal',
  'Dior Eluchil',
  'Earendil Blessed',
  'Elwing The White',
  'Elrond Peredhel',
  'Elros Tar-Minyatur',
  'Aragorn Elessar',
  'Arven Evenstar',
  'Frodo Baggins',
  'Drogo Baggins',
  'Primula Baggins',
  'Bilbo Baggins',
  'Sem Gamgee',
  'Meriadoc (Merry) Brandybuck',
  'Peregrin (Pippin) Took',
];
